# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05a10ed2f29791a69b3d886c54e03bab0456cbb8c30c6799eaa971b182c84abaa2278efb8b45f69bed16dbf98e2b4520db01d49d9eea65578024196fb10a7798

test:
  secret_key_base: 765eb3b6584686fb1c1d771e84446ea0e455ea3c0c3907c3921709b7cea08a62de89396348561a01e3ab9e7004d8e8db2fdccd03c12500433bc0a52698ec9aa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
