# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d655bec6f217622d8fb2e3003a27b6f0f740a5a95a325a539b56c473065edd4f4ea187f4ae5ddd3e26dfdb8b0e2ae88422b66236cf8ffbddcdfafd110b4aaefe

test:
  secret_key_base: 7500240c756215c2e467ef71bfc52815f795be0b89911bf67e05751fb5346e45ff9d6946dc8d1c26339715c886cb7fddbce9e9b19c2e7b411647a6a4a21abe53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
