# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbbdbeaecc26e1fcfa6326add6c0250a05a09c2ae9e5725ba90d452817bcf3cb0a3db242cbecfc8d5e547f675d289efddd3e1c37738119fa409677ac60eab691

test:
  secret_key_base: cdbe611c6b386a37f73583fd99fe6d8a33751240fc8a53a0610f03a2f7f2bb22af134bc29c0b7ea75d159a674e70145fcbc70f83259684edb31795328e419112

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
