# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e07e958de2bfcceb81b878aa6e1eb522823fbbcc6d6c4d6dcc6807c87a3c7a85a8e8f43d39008154d4b6c8b0ea109991e7dc60a273faa6ef90432d5e435360b9

test:
  secret_key_base: 7129cea3dffaa9f30847530d6d8c162b2af4d5db8ec142d83d0ad63c30067b2f7e6b7428d26ec567b5c580b91415517a4113eda6ce43a320d568e7904b9e09d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
