# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a0a74792e7189294698bff97a584d6674bc5674d3e88643bf0281e4670ce821608f158cee94c36feed3da93493ec07337f293c6a1b78f77965096550526a25b

test:
  secret_key_base: 1a7e227ce4576591fe6be00c76af06be861bb275c6481ee20a8c38c640eadd92b895b95f1574f321f0e7d50ad8eaa1950b2414f3ff4395828669ffb87cf9e9cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
