# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efc8b97e848db32dfced9319d8774ec78a5fe2946159c7d8effb93b999bf74858d9d0999fbf2d73770f94d0317b09130e3ead47636c9279becf1092663ee6ecb

test:
  secret_key_base: c01db453686f4fb815aeb09e5feabc4b8f537d7ffb71f39afb728f79df12df01266317714733130f5e8898c5cf96afe67ef886e6092747c8885d4d7fc0fc8c34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
