# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cea86edc8d59fd606280ab075ed66ae003e6ab1cb40743b67db1dd01cf69c0843cae6742c7af558d6072b7fa877f330472ec0d57e77b6ca2757b3accc7c4bf70

test:
  secret_key_base: 5a22b97a2b59019e401373d11b73bfbc877c2fa6faefcf71a990f55f9f4b5a1fc61f6205ebd69b396be2d81485336d1f65e91d407e2f353a7e3ecf67a5c58b82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
