# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 485b8f5f123dd361e20372a649b614dce8a2cfa67b2e1cd50939138b3df00fab202325852719b4d4238c82bff144ba0dff3475be57c8767cd53e76e59d98c34c

test:
  secret_key_base: bc2d9e579fd4eaca03bbbbc1ed48c4fc62433fdbac6a17c15bc8633c0c94aa0368e0b5039d97368d8e8a6c4db3fa5420389fc0e56d69c3a56a2444b385a81834

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
