# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de97412903c9852c43cdea67e6cbab261294e0dd4e80b32259c31361891567ee65a36370511ef701bfb7b5e310ce1b7235a2f3445b1345844d5aa81daef9f636

test:
  secret_key_base: 6e50ab560cf6f105414d10052b5002004895a5e5dca230d48b47c129662de0bf4167a65323d8d6a4b79aec09f81d2cac8bb7b31da339fb083989299af7fc5d83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
