# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9beb60912822a6e4b1c8c4d42f34bca8bebcb7c725cdc4ada22c23244e28d51f5a989401a5a3c73e266739dfe676708250e6335ba9dd1bfb2e0d0cd2c83e9c0c

test:
  secret_key_base: 62237be4e93cbfb8b9b5bf9aaa5fc21ffc832497a007023cc67e460b754ca4ced9d650b7852af7f4bdb692fdcaa59170e83c9f940a0013a71744a953f2694b18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
