# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8d3d15ed4986894af1a5b654031b49a66eaf5d523b34739bca68eab0d73fc759c5924bc5249c0cfe72384ce13bd973c1805f8ebbf489d2b23f84296d176f775

test:
  secret_key_base: e9e59cab98046c5a8e2fc33ce7425932375f38d4d469f4a8f15386326a12ca62a45a562320c6e53eeeb096223af6aa7ef5aafd1c54997e405d6fa3381f132a02

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
