# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b7b4168e126f59ef4fd51b3ec96f9faa083a27def2c7afb273d2a5184271b58ad5459b19449cfc6f1ff81f0a830fada63054c8e96059d37385145a55e8bb17

test:
  secret_key_base: cbf209055ed46599dbb645ee20a6108f31ac0030572e2fb5b4a8bb8574f4836f5c41a9ee314c36423f8d1d4e90ce8be54d542dc29db0c1deaa13526de44b9181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
