# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c18e4c541014b2fe4917381fca7ec1abcd4a4508ac33a35de259f3ad03b6e0b1caf7e7b6cedb24e94109ab50e55607f0b6b21214eedfb6893172e25f00ba11e

test:
  secret_key_base: f30f994308d2ebbe5614d16c06e10eb91a5cb0d0bd8070d05baa013ea500ed753c31f81bed9f02fb8fab5c141db123cee254b8bd0cca8ea1ad1351881817a155

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
