# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa309644bc5e36647aca0dcec25ea9e387a830f2405dc886a186e021e51b00df663acc12ecfefa2657e48dbbbf0239834bfe9bf7f70e29cbbd4cf7c0601237fb

test:
  secret_key_base: 4f5a169baf0b1a6cc69cb247c3fb177e0572e7335301fb3d4523948614ba560a2574823638c402f0493ee99123d4101ad341ad30d0e4bbe7a312f0a625e01dce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
