# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfdf08c3d217fda1c674f77a0edd75d2f1a58e99417e683212559b4bbc18096ca64a468acde685a45b51febace79338feeaa5c232fa23520dcda8482803c8978

test:
  secret_key_base: 542437474d1d38af26e84bcd9643fe824c7b949574ea6e79b803c809ec835c4bfe3b125878fc5090057a8a3f2d5614ea14919729a23b81ce8133165d19021b0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
