# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17cc6b855c1f52382a3ce3c7f4bf43063a2038c0d8dd6383d6d6f33e493c958642b66e76f9061dbc95bc2b1d39a00548c728bf368bb58c496a6e780204141413

test:
  secret_key_base: 8485dae925bf340f68aaec9e33b0be3d19850275b1a1f8922c402cfb005162a2ec1ca287fad26a2ac379e9468f8848b5793dda7b1bf2e467f912770c274e94fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
