# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09b84e667e64856439306995e7bd77ae062d251dffe8995d8d1e5b9275ee05499d7af6a4665eb5e048f1d0b06c2654d5247785c3273c9e8ee443df4213bd14d4

test:
  secret_key_base: e7bbadc826ab6bf0c57b4af8be9a1dfe9117f5ce0aee5213b1b0291d541e1778b7b11e0fee0aed1414454c55a34643ec03e3844ca811c7f6f909d60437def981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
