# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09825604f350cdb697bd407f35493ff410780aa418918c9a3dc193ad56dac589aa9af227f41bf6c6526b75d674c0b83766754172d746d417701c81fa92e8dd18

test:
  secret_key_base: 5bfa08fbce555f86a9691d6e82511fb6a99faef798d18fffdbe2aec3230181fa07d602a115a5a8c61baf394473f4ef15d0552fd4dcad37e37e45ece3ead215b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
