# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b191851ae4c21a421ce40716d90ebaf7ecc5fb5cd76bf567f559c2fa2aa40d53bb1be85137e8018aaaac04ad0938977fa24d19f56d4f34888915901b1f78732

test:
  secret_key_base: d95eceeb6bba6fa1bf3beca26a7ce9910623cef785d389f6954500ad2b05af8a07bf157f652307a63b2b77de424c426828ebdb3aac19e83b6c0082862437ef0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
