# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37d3ffe2817c49c172d6682228a4f3c4a90ac60025d50636b0232e9c78c0e72d473a61e024998de484b79e05e6c18012de56ac6688eaa20dc99165267ab6ed1d

test:
  secret_key_base: 49766b30be52bd4fe77df94c257dba42e10d4c2b1edd0165d65f0c45fc7968638ed82edd0405fbcda67887da865d37c349e5b496b30c655304faee821c8a0709

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
